import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import GameGrid from '../components/GameGrid'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="min-h-screen p-4">
      <Navbar />
      <div className="text-white p-10 bg-gradient-to-r from-gray-700 via-gray-900 to-black">
        <GameGrid />
      </div>
      <Footer />
    </div>
    // <div className={styles.container}>
    //   hello
    //   {/* <Head>
    //     <title>Hello World</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     hello
    //   </main>

    //   <footer className={styles.footer}>
    //     Created by Ben
    //   </footer> */}
    // </div>
  // <div className="flex min-h-screen justify-center items-center">
  //   <head>
  //     <title>Create Next App</title>
  //     <meta name="description" content="Generated by create next app" />
  //     <link rel="icon" href="/favicon.ico" />
  //   </head>

  //   <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
  //     <img
  //       className="w-full"
  //       src="https://tailwindcss.com/img/card-top.jpg"
  //       alt="Sunset in the mountains"
  //     />
  //     <div className="px-6 py-4">
  //       <div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
  //       <p className="text-grey-darker text-base">
  //         Next and Tailwind CSS are a match made in heaven, check out this article on how
  //         you can combine these two for your next app.
  //       </p>
  //     </div>
  //   </div>
  // </div>
  )
}

export default Home
